package service

// 由 tmp_cities_only.tsv 生成：断言 LITE 采样到的 CN/HK/MO/TW 城市均可中文化。
var liteCNCities = []struct{ region, city string }{
	{"Anhui", "Anqing"},
	{"Anhui", "Bengbu"},
	{"Anhui", "Bozhou"},
	{"Anhui", "Chizhou"},
	{"Anhui", "Chuzhou"},
	{"Anhui", "Fuyang"},
	{"Anhui", "Hefei"},
	{"Anhui", "Huaibei"},
	{"Anhui", "Huainan"},
	{"Anhui", "Huangshan"},
	{"Anhui", "Lu'an"},
	{"Anhui", "Ma'anshan"},
	{"Anhui", "Suzhou"},
	{"Anhui", "Tongling"},
	{"Anhui", "Wuhu"},
	{"Anhui", "Xuancheng"},
	{"Beijing", "Beijing"},
	{"Changhua", "Changhua"},
	{"Changhua", "Yuanlin"},
	{"Chiayi", "Chiayi"},
	{"Chiayi", "Taibao"},
	{"Chongqing", "Chongqing"},
	{"Fujian", "Fuqing"},
	{"Fujian", "Fuzhou"},
	{"Fujian", "Longyan"},
	{"Fujian", "Nanping"},
	{"Fujian", "Ningde"},
	{"Fujian", "Putian"},
	{"Fujian", "Quanzhou"},
	{"Fujian", "Sanming"},
	{"Fujian", "Xiamen"},
	{"Fujian", "Zhangzhou"},
	{"Gansu", "Baiyin"},
	{"Gansu", "Dingxi"},
	{"Gansu", "Jiayuguan"},
	{"Gansu", "Jinchang"},
	{"Gansu", "Jiuquan"},
	{"Gansu", "Lanzhou"},
	{"Gansu", "Linxia"},
	{"Gansu", "Longnan"},
	{"Gansu", "Pingliang"},
	{"Gansu", "Qingyang"},
	{"Gansu", "Tianshui"},
	{"Gansu", "Wuwei"},
	{"Gansu", "Zhangye"},
	{"Guangdong", "Chaozhou"},
	{"Guangdong", "Dongguan"},
	{"Guangdong", "Foshan"},
	{"Guangdong", "Guangzhou"},
	{"Guangdong", "Heyuan"},
	{"Guangdong", "Huizhou"},
	{"Guangdong", "Jiangmen"},
	{"Guangdong", "Jieyang"},
	{"Guangdong", "Maoming"},
	{"Guangdong", "Meizhou"},
	{"Guangdong", "Puning"},
	{"Guangdong", "Qingyuan"},
	{"Guangdong", "Shantou"},
	{"Guangdong", "Shanwei"},
	{"Guangdong", "Shaoguan"},
	{"Guangdong", "Shenzhen"},
	{"Guangdong", "Wuchuan"},
	{"Guangdong", "Yangjiang"},
	{"Guangdong", "Yunfu"},
	{"Guangdong", "Zhanjiang"},
	{"Guangdong", "Zhaoqing"},
	{"Guangdong", "Zhongshan"},
	{"Guangdong", "Zhuhai"},
	{"Guangxi Zhuangzu", "Baise"},
	{"Guangxi Zhuangzu", "Beihai"},
	{"Guangxi Zhuangzu", "Chongzuo"},
	{"Guangxi Zhuangzu", "Fangchenggang"},
	{"Guangxi Zhuangzu", "Guigang"},
	{"Guangxi Zhuangzu", "Guilin"},
	{"Guangxi Zhuangzu", "Hechi"},
	{"Guangxi Zhuangzu", "Hezhou"},
	{"Guangxi Zhuangzu", "Laibin"},
	{"Guangxi Zhuangzu", "Liuzhou"},
	{"Guangxi Zhuangzu", "Nanning"},
	{"Guangxi Zhuangzu", "Qinzhou"},
	{"Guangxi Zhuangzu", "Wuzhou"},
	{"Guangxi Zhuangzu", "Yulin"},
	{"Guizhou", "Anshun"},
	{"Guizhou", "Bijie"},
	{"Guizhou", "Duyun"},
	{"Guizhou", "Guiyang"},
	{"Guizhou", "Kaili"},
	{"Guizhou", "Liupanshui"},
	{"Guizhou", "Tongren"},
	{"Guizhou", "Xingyi"},
	{"Guizhou", "Zunyi"},
	{"Hainan", "Danzhou"},
	{"Hainan", "Haikou"},
	{"Hainan", "Qionghai"},
	{"Hainan", "Sanya"},
	{"Hainan", "Wenchang"},
	{"Hainan", "Wuzhishan"},
	{"Hebei", "Baoding"},
	{"Hebei", "Cangzhou"},
	{"Hebei", "Chengde"},
	{"Hebei", "Gaobeidian"},
	{"Hebei", "Handan"},
	{"Hebei", "Hengshui"},
	{"Hebei", "Langfang"},
	{"Hebei", "Qinhuangdao"},
	{"Hebei", "Renqiu"},
	{"Hebei", "Shijiazhuang"},
	{"Hebei", "Tangshan"},
	{"Hebei", "Xingtai"},
	{"Hebei", "Zhangjiakou"},
	{"Hebei", "Zhuozhou"},
	{"Hebei", "Zunhua"},
	{"Heilongjiang", "Daqing"},
	{"Heilongjiang", "Harbin"},
	{"Heilongjiang", "Hegang"},
	{"Heilongjiang", "Heihe"},
	{"Heilongjiang", "Jiamusi"},
	{"Heilongjiang", "Jixi"},
	{"Heilongjiang", "Mudanjiang"},
	{"Heilongjiang", "Qiqihar"},
	{"Heilongjiang", "Qitaihe"},
	{"Heilongjiang", "Shuangyashan"},
	{"Heilongjiang", "Suihua"},
	{"Heilongjiang", "Yichun"},
	{"Henan", "Anyang"},
	{"Henan", "Gongyi"},
	{"Henan", "Hebi"},
	{"Henan", "Jiaozuo"},
	{"Henan", "Jiyuan"},
	{"Henan", "Kaifeng"},
	{"Henan", "Luohe"},
	{"Henan", "Luoyang"},
	{"Henan", "Nanyang"},
	{"Henan", "Pingdingshan"},
	{"Henan", "Puyang"},
	{"Henan", "Sanmenxia"},
	{"Henan", "Shangqiu"},
	{"Henan", "Xinxiang"},
	{"Henan", "Xinyang"},
	{"Henan", "Xuchang"},
	{"Henan", "Zhengzhou"},
	{"Henan", "Zhoukou"},
	{"Henan", "Zhumadian"},
	{"Hong Kong", "Hong Kong"},
	{"Hong Kong", "Kuk Liu"},
	{"Hong Kong", "Lo So Shing"},
	{"Hong Kong", "Pan Long Wan"},
	{"Hong Kong", "Tai Wong Ha"},
	{"Hong Kong", "To Fung Shan"},
	{"Hong Kong", "Tsim Sha Tsui"},
	{"Hong Kong", "Wong Fung Leng"},
	{"Hsinchu", "Hsinchu"},
	{"Hualien", "Hualien"},
	{"Hubei", "Enshi"},
	{"Hubei", "Ezhou"},
	{"Hubei", "Huanggang"},
	{"Hubei", "Huangshi"},
	{"Hubei", "Jingmen"},
	{"Hubei", "Jingzhou"},
	{"Hubei", "Lichuan"},
	{"Hubei", "Qianjiang"},
	{"Hubei", "Shiyan"},
	{"Hubei", "Suizhou"},
	{"Hubei", "Tianmen"},
	{"Hubei", "Wuhan"},
	{"Hubei", "Xiangyang"},
	{"Hubei", "Xianning"},
	{"Hubei", "Xiantao"},
	{"Hubei", "Xiaogan"},
	{"Hubei", "Yichang"},
	{"Hunan", "Changde"},
	{"Hunan", "Changsha"},
	{"Hunan", "Chenzhou"},
	{"Hunan", "Hengyang"},
	{"Hunan", "Huaihua"},
	{"Hunan", "Jishou"},
	{"Hunan", "Loudi"},
	{"Hunan", "Shaoyang"},
	{"Hunan", "Xiangtan"},
	{"Hunan", "Yiyang"},
	{"Hunan", "Yongzhou"},
	{"Hunan", "Yueyang"},
	{"Hunan", "Zhangjiajie"},
	{"Hunan", "Zhuzhou"},
	{"Jiangsu", "Changzhou"},
	{"Jiangsu", "Huai'an"},
	{"Jiangsu", "Lianyungang"},
	{"Jiangsu", "Nanjing"},
	{"Jiangsu", "Nantong"},
	{"Jiangsu", "Suqian"},
	{"Jiangsu", "Suzhou"},
	{"Jiangsu", "Taizhou"},
	{"Jiangsu", "Wuxi"},
	{"Jiangsu", "Xuzhou"},
	{"Jiangsu", "Yancheng"},
	{"Jiangsu", "Yangzhou"},
	{"Jiangsu", "Zhenjiang"},
	{"Jiangxi", "Fuzhou"},
	{"Jiangxi", "Ganzhou"},
	{"Jiangxi", "Ji'an"},
	{"Jiangxi", "Jingdezhen"},
	{"Jiangxi", "Jiujiang"},
	{"Jiangxi", "Longnan"},
	{"Jiangxi", "Nanchang"},
	{"Jiangxi", "Pingxiang"},
	{"Jiangxi", "Shangrao"},
	{"Jiangxi", "Xinyu"},
	{"Jiangxi", "Yichun"},
	{"Jiangxi", "Yingtan"},
	{"Jiangxi", "Zhangshu"},
	{"Jilin", "Baicheng"},
	{"Jilin", "Baishan"},
	{"Jilin", "Changchun"},
	{"Jilin", "Jilin"},
	{"Jilin", "Liaoyuan"},
	{"Jilin", "Siping"},
	{"Jilin", "Songyuan"},
	{"Jilin", "Tonghua"},
	{"Jilin", "Yanji"},
	{"Kaohsiung", "Kaohsiung"},
	{"Keelung", "Keelung"},
	{"Kinmen", "Jincheng"},
	{"Liaoning", "Anshan"},
	{"Liaoning", "Benxi"},
	{"Liaoning", "Chaoyang"},
	{"Liaoning", "Dalian"},
	{"Liaoning", "Dandong"},
	{"Liaoning", "Fushun"},
	{"Liaoning", "Fuxin"},
	{"Liaoning", "Huludao"},
	{"Liaoning", "Jinzhou"},
	{"Liaoning", "Liaoyang"},
	{"Liaoning", "Panjin"},
	{"Liaoning", "Shenyang"},
	{"Liaoning", "Tieling"},
	{"Liaoning", "Wafangdian"},
	{"Liaoning", "Yingkou"},
	{"Lienchiang", "Nangan"},
	{"Macao", "Macau"},
	{"Miaoli", "Miaoli"},
	{"Nantou", "Nantou"},
	{"Nantou", "Puli"},
	{"Nei Mongol", "Baotou"},
	{"Nei Mongol", "Bayannur"},
	{"Nei Mongol", "Chifeng"},
	{"Nei Mongol", "Hohhot"},
	{"Nei Mongol", "Hulunbuir"},
	{"Nei Mongol", "Ordos"},
	{"Nei Mongol", "Tongliao"},
	{"Nei Mongol", "Ulanhot"},
	{"Nei Mongol", "Ulanqab"},
	{"Nei Mongol", "Wuhai"},
	{"Nei Mongol", "Xilinhot"},
	{"New Taipei", "Banqiao"},
	{"Ningxia Huizu", "Guyuan"},
	{"Ningxia Huizu", "Shizuishan"},
	{"Ningxia Huizu", "Wuzhong"},
	{"Ningxia Huizu", "Yinchuan"},
	{"Ningxia Huizu", "Zhongwei"},
	{"Penghu", "Magong"},
	{"Pingtung", "Hengchun"},
	{"Pingtung", "Pingtung"},
	{"Qinghai", "Delingha"},
	{"Qinghai", "Haidong"},
	{"Qinghai", "Xining"},
	{"Qinghai", "Yushu"},
	{"Shaanxi", "Ankang"},
	{"Shaanxi", "Baoji"},
	{"Shaanxi", "Hanzhong"},
	{"Shaanxi", "Shangluo"},
	{"Shaanxi", "Tongchuan"},
	{"Shaanxi", "Weinan"},
	{"Shaanxi", "Xi'an"},
	{"Shaanxi", "Xianyang"},
	{"Shaanxi", "Yan'an"},
	{"Shaanxi", "Yulin"},
	{"Shandong", "Binzhou"},
	{"Shandong", "Dezhou"},
	{"Shandong", "Dongying"},
	{"Shandong", "Heze"},
	{"Shandong", "Jinan"},
	{"Shandong", "Jining"},
	{"Shandong", "Laiyang"},
	{"Shandong", "Liaocheng"},
	{"Shandong", "Linqing"},
	{"Shandong", "Linyi"},
	{"Shandong", "Qingdao"},
	{"Shandong", "Rizhao"},
	{"Shandong", "Tai'an"},
	{"Shandong", "Weifang"},
	{"Shandong", "Weihai"},
	{"Shandong", "Yantai"},
	{"Shandong", "Zaozhuang"},
	{"Shandong", "Zibo"},
	{"Shanghai", "Shanghai"},
	{"Shanxi", "Changzhi"},
	{"Shanxi", "Datong"},
	{"Shanxi", "Fenyang"},
	{"Shanxi", "Jincheng"},
	{"Shanxi", "Jinzhong"},
	{"Shanxi", "Linfen"},
	{"Shanxi", "Shuozhou"},
	{"Shanxi", "Taiyuan"},
	{"Shanxi", "Xinzhou"},
	{"Shanxi", "Yangquan"},
	{"Shanxi", "Yuncheng"},
	{"Sichuan", "Barkam"},
	{"Sichuan", "Bazhong"},
	{"Sichuan", "Chengdu"},
	{"Sichuan", "Dazhou"},
	{"Sichuan", "Deyang"},
	{"Sichuan", "Emeishan"},
	{"Sichuan", "Guang'an"},
	{"Sichuan", "Guangyuan"},
	{"Sichuan", "Kangding"},
	{"Sichuan", "Leshan"},
	{"Sichuan", "Luzhou"},
	{"Sichuan", "Meishan"},
	{"Sichuan", "Mianyang"},
	{"Sichuan", "Nanchong"},
	{"Sichuan", "Neijiang"},
	{"Sichuan", "Panzhihua"},
	{"Sichuan", "Pengzhou"},
	{"Sichuan", "Suining"},
	{"Sichuan", "Xichang"},
	{"Sichuan", "Ya'an"},
	{"Sichuan", "Yibin"},
	{"Sichuan", "Zigong"},
	{"Sichuan", "Ziyang"},
	{"Taichung", "Taichung"},
	{"Tainan", "Tainan"},
	{"Tainan", "Xinying"},
	{"Tainan", "Yujing"},
	{"Taipei", "Taipei"},
	{"Taitung", "Taitung"},
	{"Taoyuan", "Taoyuan"},
	{"Tianjin", "Tianjin"},
	{"Xinjiang Uygur", "Aksu"},
	{"Xinjiang Uygur", "Altay"},
	{"Xinjiang Uygur", "Beitun"},
	{"Xinjiang Uygur", "Bole"},
	{"Xinjiang Uygur", "Changji"},
	{"Xinjiang Uygur", "Hami"},
	{"Xinjiang Uygur", "Hotan"},
	{"Xinjiang Uygur", "Karamay"},
	{"Xinjiang Uygur", "Kashgar"},
	{"Xinjiang Uygur", "Korla"},
	{"Xinjiang Uygur", "Kuytun"},
	{"Xinjiang Uygur", "Shihezi"},
	{"Xinjiang Uygur", "Tacheng"},
	{"Xinjiang Uygur", "Turpan"},
	{"Xizang", "Lhasa"},
	{"Xizang", "Nagqu"},
	{"Xizang", "Qamdo"},
	{"Xizang", "Shannan"},
	{"Yilan", "Yilan"},
	{"Yunlin", "Douliu"},
	{"Yunnan", "Baoshan"},
	{"Yunnan", "Chuxiong"},
	{"Yunnan", "Dali"},
	{"Yunnan", "Honghe"},
	{"Yunnan", "Jinghong"},
	{"Yunnan", "Kunming"},
	{"Yunnan", "Lijiang"},
	{"Yunnan", "Lincang"},
	{"Yunnan", "Mangshi"},
	{"Yunnan", "Pu'er"},
	{"Yunnan", "Qujing"},
	{"Yunnan", "Wenshan"},
	{"Yunnan", "Yuxi"},
	{"Yunnan", "Zhaotong"},
	{"Zhejiang", "Haining"},
	{"Zhejiang", "Hangzhou"},
	{"Zhejiang", "Huzhou"},
	{"Zhejiang", "Jiaxing"},
	{"Zhejiang", "Jinhua"},
	{"Zhejiang", "Lishui"},
	{"Zhejiang", "Ningbo"},
	{"Zhejiang", "Quzhou"},
	{"Zhejiang", "Shaoxing"},
	{"Zhejiang", "Taizhou"},
	{"Zhejiang", "Wenling"},
	{"Zhejiang", "Wenzhou"},
	{"Zhejiang", "Yiwu"},
	{"Zhejiang", "Yuyao"},
	{"Zhejiang", "Zhoushan"},
	{"Zhejiang", "Zhuji"},
}
